export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//project types
export const CREATE_PROJECT_LOADING = 'CREATE_PROJECT_LOADING';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';


export const GET_PROJECTS_LOADING = 'GET_PROJECTS_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

//get one project b id
export const GET_ONE_ROJECT_LOADING = 'GET_ONE_ROJECT_LOADING';
export const GET_ONE_ROJECT_SUCCESS = 'GET_ONE_ROJECT_SUCCESS';
export const GET_ONE_ROJECT_FAIL = 'GET_ONE_ROJECT_FAIL';
export const RESET_SELeCTED_PROJECT = 'RESET_SELeCTED_PROJECT';


//update
export const UPDATE_PROJECT_LOAD = 'UPDATE_PROJECT_LOAD';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

//delete project
export const DELETE_PROJECT_LOAD = 'DELETE_PROJECT_LOAD';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';